### ISSUE TITLE
YouTube Takes Down Replys

### ISSUE THREAD

**Issue by sjacksonhodum** [upiir/custom_boost_gauge_esp32#1]
Hello. I’m not sure if you remember me or not. I’m that kid that needs assistance on his project. I keep trying to reply on YouTube, but it won’t let me. Can you please message me on discord @sfpv. Thanks

**Comment by upiir** [comment]
Hello, I´m sorry about youtube comments, it´s strange but possible. Please send me an email, it´s on the about page of the youtube channel.

**Comment by skunkfpv** [comment]
Sorry but I don't see the email on your about page

**Comment by sjacksonhodum** [comment]
> Hello, I´m sorry about youtube comments, it´s strange but possible. Please send me an email, it´s on the about page of the youtube channel. 

I sent the email
